CREATE TABLE IF NOT EXISTS community(
  id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL
);

INSERT INTO community(id, name) VALUES('a3bb3d66-b3fc-4549-841e-d9ad1a3db0e6', 'Sample Community');

ALTER TABLE IF EXISTS admin    ADD COLUMN community_id UUID REFERENCES community(id) ON DELETE CASCADE NOT NULL DEFAULT 'a3bb3d66-b3fc-4549-841e-d9ad1a3db0e6';
ALTER TABLE IF EXISTS resident ADD COLUMN community_id UUID REFERENCES community(id) ON DELETE CASCADE NOT NULL DEFAULT 'a3bb3d66-b3fc-4549-841e-d9ad1a3db0e6';
ALTER TABLE IF EXISTS car      ADD COLUMN community_id UUID REFERENCES community(id) ON DELETE CASCADE NOT NULL DEFAULT 'a3bb3d66-b3fc-4549-841e-d9ad1a3db0e6';
ALTER TABLE IF EXISTS permit   ADD COLUMN community_id UUID REFERENCES community(id) ON DELETE CASCADE NOT NULL DEFAULT 'a3bb3d66-b3fc-4549-841e-d9ad1a3db0e6';
ALTER TABLE IF EXISTS visitor  ADD COLUMN community_id UUID REFERENCES community(id) ON DELETE CASCADE NOT NULL DEFAULT 'a3bb3d66-b3fc-4549-841e-d9ad1a3db0e6';
