BEGIN;

DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS residents CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS permits CASCADE;

COMMIT;
