BEGIN;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS admins(
  id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  is_privileged BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS residents(
  id CHAR(8) PRIMARY KEY UNIQUE NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone VARCHAR(15) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  unlim_days BOOLEAN NOT NULL DEFAULT FALSE,
  amt_parking_days_used SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cars(
  id UUID PRIMARY KEY UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
  license_plate VARCHAR(10) UNIQUE NOT NULL,
  color TEXT NOT NULL,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS permits(
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  resident_id CHAR(8) REFERENCES residents(id) ON DELETE CASCADE NOT NULL,
  car_id UUID REFERENCES cars(id) ON DELETE CASCADE NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  request_ts BIGINT,
  affects_days BOOLEAN NOT NULL
);

COMMIT;
