BEGIN;

DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS resident CASCADE;
DROP TABLE IF EXISTS car CASCADE;
DROP TABLE IF EXISTS permit CASCADE;

COMMIT;
