INSERT INTO permit_exception(permit_id, reason) VALUES( 1, 'Flash photography is best used in full sunlight.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 3, 'I am counting my calories, yet I really want dessert.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 5, 'I love eating toasted cheese and tuna sandwiches.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 7, 'It''s not often you find a soggy banana on the street.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 9, 'If my calculator had a history, it would be more embarrassing than my browser history.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 11, 'It took him a while to realize that everything he decided not to change, he was actually choosing.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 13, 'There was no ice cream in the freezer, nor did they have money to go to the store.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 15, 'The bullet pierced the window shattering it before missing Danny''s head by mere millimeters.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 16, 'The hand sanitizer was actually clear glue.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 17, 'He was the only member of the club who didn''t like plum pudding.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 18, 'His son quipped that power bars were nothing more than adult candy bars.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 19, 'David proudly graduated from high school top of his class at age 97.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 20, 'The balloons floated away along with all my hopes and dreams.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 22, 'The efficiency with which he paired the socks in the drawer was quite admirable.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 23, 'When motorists sped in and out of traffic, all she could think of was those in need of a transplant.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 24, 'The beauty of the African sunset disguised the danger lurking nearby.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 26, 'The urgent care center was flooded with patients after the news of a new deadly virus was made public.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 27, 'I often see the time 11:11 or 12:34 on clocks.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 28, 'Nancy decided to make the porta-potty her home.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 31, 'Plans for this weekend include turning wine into water.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 32, 'She discovered van life is difficult with 2 cats and a dog.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 34, 'He embraced his new life as an eggplant.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 36, 'He had accidentally hacked into his company''s server.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 37, 'With a single flip of the coin, his life changed forever.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 38, 'Always bring cinnamon buns on a deep-sea diving expedition.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 42, 'No matter how beautiful the sunset, it saddened her knowing she was one day older.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 44, 'She had convinced her kids that any mushroom found on the ground would kill them if they touched it.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 46, 'He had a wall full of masks so she could wear a different face every day.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 47, 'It must be easy to commit crimes as a snake because you don''t have to worry about leaving fingerprints.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 51, 'Mr. Montoya knows the way to the bakery even though he''s never been there.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 53, 'As the rental car rolled to a stop on the dark road, her fear increased by the moment.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 54, 'I honestly find her about as intimidating as a basket of kittens.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 55, 'The doll spun around in circles in hopes of coming alive.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 58, 'Seek success, but always be prepared for random cats.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 59, 'She lived on Monkey Jungle Road and that seemed to explain all of her strangeness.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 60, 'They called out her name time and again, but were met with nothing but silence.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 62, 'She always had an interesting perspective on why the world must be flat.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 65, 'After fighting off the alligator, Brian still had to face the anaconda.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 66, 'That must be the tenth time I''ve been arrested for selling deep-fried cigars.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 68, 'Combines are no longer just for farms.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 69, 'He barked orders at his daughters but they just stared back with amusement.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 77, 'The best part of marriage is animal crackers with peanut butter.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 78, 'The fish dreamed of escaping the fishbowl and into the toilet where he saw his friend go.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 81, 'The ice-cream trucks bring back bad memories for all of us.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 82, 'He ran out of money, so he had to stop playing poker.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 83, 'Toddlers feeding raccoons surprised even the seasoned park ranger.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 84, 'Had he known what was going to happen, he would have never stepped into the shower.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 85, 'While all her friends were positive that Mary had a sixth sense, she knew she actually had a seventh sense.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 86, 'The pigs were insulted that they were named hamburgers.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 87, 'There''s a message for you if you look up');
INSERT INTO permit_exception(permit_id, reason) VALUES( 94, 'They desperately needed another drummer since the current one only knew how to play bongos.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 95, 'He learned the hardest lesson of his life and had the scars, both physical and mental, to prove it.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 96, 'The bug was having an excellent day until he hit the windshield.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 99, 'They ran around the corner to find that they had traveled back in time.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 100, 'When he had to picnic on the beach, he purposely put sand in other people’s food.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 104, 'All they could see was the blue water surrounding their sailboat.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 111, 'It was a really good Monday for being a Saturday.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 112, 'I would be delighted if the sea were full of cucumber juice.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 113, 'With the high wind warning');
INSERT INTO permit_exception(permit_id, reason) VALUES( 114, 'The father died during childbirth.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 116, 'Greetings from the galaxy MACS0647-JD, or what we call home.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 119, 'He didn''t heed the warning and it had turned out surprisingly well.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 120, 'The efficiency with which he paired the socks in the drawer was quite admirable.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 121, 'Waffles are always better without fire ants and fleas.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 126, 'Mary plays the piano.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 128, 'They were excited to see their first sloth.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 130, 'He loved eating his bananas in hot dog buns.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 131, 'The near-death experience brought new ideas to light.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 133, 'I want to buy a onesie… but know it won’t suit me.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 134, 'The tour bus was packed with teenage girls heading toward their next adventure.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 135, 'The group quickly understood that toxic waste was the most effective barrier to use against the zombies.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 136, 'He figured a few sticks of dynamite were easier than a fishing pole to catch fish.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 137, 'The shooter says goodbye to his love.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 138, 'He was sure the Devil created red sparkly glitter.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 145, 'He uses onomatopoeia as a weapon of mental destruction.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 150, 'The beauty of the sunset was obscured by the industrial cranes.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 151, 'Seek success, but always be prepared for random cats.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 152, 'Smoky the Bear secretly started the fires.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 156, 'The hummingbird''s wings blurred while it eagerly sipped the sugar water from the feeder.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 159, 'The sight of his goatee made me want to run and hide under my sister-in-law''s bed.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 162, 'You have no right to call yourself creative until you look at a trowel and think that it would make a great lockpick.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 163, 'Last Friday I saw a spotted striped blue worm shake hands with a legless lizard.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 165, 'He wondered why at 18 he was old enough to go to war, but not old enough to buy cigarettes.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 167, 'The view from the lighthouse excited even the most seasoned traveler.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 168, 'It''s a skateboarding penguin with a sunhat!');
INSERT INTO permit_exception(permit_id, reason) VALUES( 170, 'Beach-combing replaced wine tasting as his new obsession.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 172, 'Check back tomorrow; I will see if the book has arrived.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 175, 'He found rain fascinating yet unpleasant.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 176, 'When money was tight, he''d get his lunch money from the local wishing well.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 177, 'It didn''t take long for Gary to detect the robbers were amateurs.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 178, 'Warm beer on a cold day isn''t my idea of fun.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 183, 'She hadn''t had her cup of coffee, and that made things all the worse.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 184, 'The old rusted farm equipment surrounded the house predicting its demise.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 187, 'Patricia loves the sound of nails strongly pressed against the chalkboard.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 189, 'He is good at eating pickles and telling women about his emotional problems.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 191, 'You can''t compare apples and oranges, but what about bananas and plantains?');
INSERT INTO permit_exception(permit_id, reason) VALUES( 193, 'You''re good at English when you know the difference between a man eating chicken and a man-eating chicken.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 194, 'Lets all be unique together until we realise we are all the same.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 196, 'The rain pelted the windshield as the darkness engulfed us.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 199, '100 years old is such a young age if you happen to be a bristlecone pine.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 204, 'He realized there had been several deaths on this road, but his concern rose when he saw the exact number.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 206, 'I come from a tribe of head-hunters, so I will never need a shrink.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 207, 'Love is not like pizza.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 210, 'He ran out of money, so he had to stop playing poker.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 213, 'He hated that he loved what she hated about hate.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 214, 'He used to get confused between soldiers and shoulders, but as a military man, he now soldiers responsibility.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 215, 'Everything was going so well until I was accosted by a purple giraffe.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 218, 'The door slammed on the watermelon.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 225, 'She lived on Monkey Jungle Road and that seemed to explain all of her strangeness.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 226, 'So long and thanks for the fish.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 227, 'They were excited to see their first sloth.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 230, 'The doll spun around in circles in hopes of coming alive.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 231, 'He colored deep space a soft yellow.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 233, 'Flesh-colored yoga pants were far worse than even he feared.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 234, 'Having no hair made him look even hairier.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 239, 'The pigs were insulted that they were named hamburgers.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 241, 'The lyrics of the song sounded like fingernails on a chalkboard.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 249, 'While all her friends were positive that Mary had a sixth sense, she knew she actually had a seventh sense.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 250, 'The near-death experience brought new ideas to light.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 254, 'He had a hidden stash underneath the floorboards in the back room of the house.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 255, 'He knew it was going to be a bad day when he saw mountain lions roaming the streets.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 256, 'Nobody loves a pig wearing lipstick.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 257, 'Imagine his surprise when he discovered that the safe was full of pudding.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 258, 'Sometimes you have to just give up and win by cheating.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 259, 'The child’s favorite Christmas gift was the large box her father’s lawnmower came in.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 261, 'I think I will buy the red car, or I will lease the blue one.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 262, 'Giving directions that the mountains are to the west only works when you can see them.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 263, 'He went on a whiskey diet and immediately lost three days.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 264, 'Her daily goal was to improve on yesterday.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 266, 'We have never been to Asia, nor have we visited Africa.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 269, 'Peter found road kill an excellent way to save money on dinner.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 270, 'She had convinced her kids that any mushroom found on the ground would kill them if they touched it.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 271, 'Please put on these earmuffs because I can''t you hear.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 272, 'She saw the brake lights, but not in time.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 276, 'It doesn''t sound like that will ever be on my travel list.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 277, 'Potato wedges probably are not best for relationships.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 278, 'There''s an art to getting your way, and spitting olive pits across the table isn''t it.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 281, 'Nancy was proud that she ran a tight shipwreck.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 283, 'Patricia loves the sound of nails strongly pressed against the chalkboard.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 284, 'She thought there''d be sufficient time if she hid her watch.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 287, 'If you really strain your ears, you can just about hear the sound of no one giving a damn.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 290, 'It took me too long to realize that the ceiling hadn''t been painted to look like the sky.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 291, 'The bullet pierced the window shattering it before missing Danny''s head by mere millimeters.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 292, 'The bird had a belief that it was really a groundhog.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 293, 'It isn''t difficult to do a handstand if you just stand on your hands.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 296, 'I love bacon, beer, birds, and baboons.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 297, 'Purple is the best city in the forest.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 298, 'There''s probably enough glass in my cupboard to build an undersea aquarium.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 300, 'He was 100% into fasting with her until he understood that meant he couldn''t eat.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 301, 'Her hair was windswept as she rode in the black convertible.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 305, 'Boulders lined the side of the road foretelling what could come next.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 306, 'The newly planted trees were held up by wooden frames in hopes they could survive the next storm.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 308, 'Their argument could be heard across the parking lot.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 310, 'Everything was going so well until I was accosted by a purple giraffe.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 312, 'Dan took the deep dive down the rabbit hole.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 313, 'All you need to do is pick up the pen and begin.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 317, 'Joyce enjoyed eating pancakes with ketchup.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 319, 'Tomatoes make great weapons when water balloons aren’t available.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 323, 'Edith could decide if she should paint her teeth or brush her nails.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 326, 'Greetings from the real universe.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 327, 'We have never been to Asia, nor have we visited Africa.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 328, 'That was how he came to win $1 million.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 334, 'In that instant, everything changed.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 335, 'Today is the day I''ll finally know what brick tastes like.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 336, 'Before he moved to the inner city, he had always believed that security complexes were psychological.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 338, 'Please tell me you don''t work in a morgue.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 339, 'At last');
INSERT INTO permit_exception(permit_id, reason) VALUES( 340, 'There''s a growing trend among teenagers of using frisbees as go-cart wheels.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 343, 'Toddlers feeding raccoons surprised even the seasoned park ranger.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 345, 'I never knew what hardship looked like until it started raining bowling balls.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 346, 'The Tsunami wave crashed against the raised houses and broke the pilings as if they were toothpicks.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 347, 'Harrold felt confident that nobody would ever suspect his spy pigeon.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 350, 'She had convinced her kids that any mushroom found on the ground would kill them if they touched it.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 352, 'She had some amazing news to share but nobody to share it with.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 353, 'Eating eggs on Thursday for choir practice was recommended.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 358, 'Courage and stupidity were all he had.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 359, 'He didn''t heed the warning and it had turned out surprisingly well.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 360, 'Whenever he saw a red flag warning at the beach he grabbed his surfboard.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 361, 'The fact that there''s a stairway to heaven and a highway to hell explains life well.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 363, 'The fog was so dense even a laser decided it wasn''t worth the effort.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 365, 'I used to practice weaving with spaghetti three hours a day but stopped because I didn''t want to die alone.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 368, 'The manager of the fruit stand always sat and only sold vegetables.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 369, 'When motorists sped in and out of traffic, all she could think of was those in need of a transplant.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 370, 'I’m a living furnace.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 371, 'I only enjoy window shopping when the windows are transparent.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 375, 'Too many prisons have become early coffins.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 376, 'Tom got a small piece of pie.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 380, '8% of 25 is the same as 25% of 8 and one of them is much easier to do in your head.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 383, 'Charles ate the french fries knowing they would be his last meal.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 386, 'She had a difficult time owning up to her own crazy self.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 388, 'They say people remember important moments in their life well, yet no one even remembers their own birth.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 390, 'Iguanas were falling out of the trees.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 391, 'The rain pelted the windshield as the darkness engulfed us.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 395, 'There were white out conditions in the town; subsequently, the roads were impassable.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 398, 'He found rain fascinating yet unpleasant.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 399, 'My Mum tries to be cool by saying that she likes all the same things that I do.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 400, 'It was always dangerous to drive with him since he insisted the safety cones were a slalom course.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 403, 'He was willing to find the depths of the rabbit hole in order to be with her.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 404, 'Malls are great places to shop; I can find everything I need under one roof.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 405, 'Andy loved to sleep on a bed of nails.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 406, 'It was the best sandcastle he had ever seen.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 407, 'Flesh-colored yoga pants were far worse than even he feared.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 408, 'Thirty years later, she still thought it was okay to put the toilet paper roll under rather than over.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 409, 'They throw cabbage that turns your brain into emotional baggage.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 411, 'The wake behind the boat told of the past while the open sea for told life in the unknown future.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 412, 'This book is sure to liquefy your brain.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 413, 'It was at that moment that he learned there are certain parts of the body that you should never Nair.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 414, 'He decided that the time had come to be stronger than any of the excuses he''d used until then.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 415, 'She hadn''t had her cup of coffee, and that made things all the worse.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 416, 'The hand sanitizer was actually clear glue.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 420, 'Nobody has encountered an explosive daisy and lived to tell the tale.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 421, 'He is no James Bond; his name is Roger Moore.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 423, 'I ate a sock because people on the Internet told me to.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 426, 'I can''t believe this is the eighth time I''m smashing open my piggy bank on the same day!');
INSERT INTO permit_exception(permit_id, reason) VALUES( 428, 'The body piercing didn''t go exactly as he expected.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 429, 'At that moment she realized she had a sixth sense.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 430, 'Little Red Riding Hood decided to wear orange today.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 431, 'The small white buoys marked the location of hundreds of crab pots.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 437, 'Sixty-Four comes asking for bread.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 438, 'Separation anxiety is what happens when you can''t find your phone.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 439, 'When transplanting seedlings, candied teapots will make the task easier.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 440, 'Most shark attacks occur about 10 feet from the beach since that''s where the people are.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 442, 'It turns out you don''t need all that stuff you insisted you did.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 444, 'So long and thanks for the fish.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 446, 'The elephant didn''t want to talk about the person in the room.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 449, 'It''s important to remember to be aware of rampaging grizzly bears.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 451, 'Your girlfriend bought your favorite cookie crisp cereal but forgot to get milk.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 452, 'The ants enjoyed the barbecue more than the family.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 454, 'Karen believed all traffic laws should be obeyed by all except herself.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 455, 'You realize you''re not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with Grandpa Joe in the hospital.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 457, 'The bees decided to have a mutiny against their queen.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 458, 'As he entered the church he could hear the soft voice of someone whispering into a cell phone.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 460, 'He set out for a short walk, but now all he could see were mangroves and water were for miles.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 462, 'He had accidentally hacked into his company''s server.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 466, 'He stomped on his fruit loops and thus became a cereal killer.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 467, 'It caught him off guard that space smelled of seared steak.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 471, 'The reservoir water level continued to lower while we enjoyed our long shower.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 472, 'They looked up at the sky and saw a million stars.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 473, 'The toddler’s endless tantrum caused the entire plane anxiety.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 474, 'He was sure the Devil created red sparkly glitter.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 477, 'The crowd yells and screams for more memes.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 478, 'Watching the geriatric men’s softball team brought back memories of 3 yr olds playing t-ball.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 479, 'The skeleton had skeletons of his own in the closet.');
INSERT INTO permit_exception(permit_id, reason) VALUES( 480, 'Smoky the Bear secretly started the fires.');
